version: '3.9'

services:
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    depends_on:
      - influxdb
    volumes:
      - ./telegraf/config:/etc/telegraf:ro
      - ./telegraf/mibs:/usr/share/snmp/mibs:ro
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_DB=telegraf

  influxdb:
    image: influxdb:1.8.2
    container_name: influxdb
    restart: always
    environment: 
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - influxdb_vol:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    environment: 
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    ports:
      - "3000:3000"
    volumes:
      - grafana_vol:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning/
      - ./grafana/dashboards:/var/lib/grafana/dashboards/

volumes:
  grafana_vol:
  influxdb_vol:

