{
 "title": "Azure Loadbalancer",
 "description": "Use Azure Loadbalancer Monitor ",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Subscriptions",
    "label": "Subscriptions",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "ResourceGroup",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "ResourceName",
    "label": "ResourceName",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SYN Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SYNCount",
      "metricNamespace": "microsoft.network/loadbalancers",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Packet Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "PacketCount",
      "metricNamespace": "microsoft.network/loadbalancers",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Byte Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ByteCount",
      "metricNamespace": "microsoft.network/loadbalancers",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "SNAT Connection Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SnatConnectionCount",
      "metricNamespace": "microsoft.network/loadbalancers",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Data Path Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "VipAvailability",
      "metricNamespace": "microsoft.network/loadbalancers",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Health Probe Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "DipAvailability",
      "metricNamespace": "microsoft.network/loadbalancers",
      "resources": [
       { "resourceGroup": "$ResourceGroup", "resourceName": "$ResourceName" }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  }
 ]
}