# config file version
apiVersion: 1

list of datasources that should be deleted from the database
deleteDatasources:
  - name: InfluxDB
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
- name: InfluxDB
  type: influxdb
  access: proxy
  orgId: 1
  url: http://influxdb:8086
  user: "admin"
  password: "PaloAlto1"
  database: "influxdb"
  basicAuth: false
  isDefault: true
  jsonData:
    timeInterval: "5s"
    graphiteVersion: "1.1"
    tlsAuth: false
    tlsAuthWithCACert: false
 # <string> json object of data that will be encrypted.
 secureJsonData:
   tlsCACert: "..."
   tlsClientCert: "..."
   tlsClientKey: "..."
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: false